apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: cbn-ingress
spec:
  rules:
  - host: cbn-biodiversity.nrp-nautilus.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cbn-svc
            port:
              number: 8080
  tls:
  - hosts:
    - cbn-biodiversity.nrp-nautilus.io
